name = "HealpixTransform"
uuid = "87ff4591-92fd-4060-b5b1-4df480ce5401"
authors = ["Ethan Anderes <anderes@ucdavis.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
